//
//  XCWorkspace.swift
//  
//
//  Created by Max Chuquimia on 1/2/2023.
//

import Foundation

struct XCWorkspace {

    let file: FileManager.Path
    let options: XCGrapherOptions

    func referencesList() throws -> [FileManager.Path] {
        try execute()
            .breakIntoLines()
            .filter { !$0.isEmpty }
    }

    func xcodeProjectList() throws -> [FileManager.Path] {
        try referencesList()
            .filter { path in
                path.hasSuffix(".xcodeproj")
            }
    }

    func fakeHeaderFile() throws -> FileManager.Path {
        let xcodeTargets = try xcodeProjectList()
            .flatMap { path in
                try XcodeprojTargets(projectFile: path).targetList()
            }

        let spmTargets = try swiftPackagesList()
            .flatMap { path in
                try SwiftPackage(clone: path).targets()
            }
            .map(\.name)

        let fakeFilePath = "/tmp/WorkspaceHeader.swift"
        var fakeFile =
        """
        // Generated by XCGrapher.
        // This file is a kind of "header" for \(file).
        // It imports all targets discovered in the workspace to provide a starting point for XCGrapher.


        """
        for target in xcodeTargets + spmTargets {
            fakeFile.append("import " + target + "\n")
        }

        try fakeFile
            .data(using: .utf8)!
            .write(to: URL(fileURLWithPath: fakeFilePath))

        return fakeFilePath
    }

    func swiftPackagesList() throws -> [FileManager.Path] {
        try referencesList()
            .filter { path in
                FileManager.default.fileExists(atPath: path.appendingPathComponent("Package.swift"))
            }
    }

}

extension XCWorkspace: ShellTask {

    var stringRepresentation: String {
        "ruby -r xcodeproj -e 'Xcodeproj::Workspace.new_from_xcworkspace(\"\(file)\").schemes.each do |s| puts s[1] end'"
    }

    var commandNotFoundInstructions: String {
        "Missing command 'xcodeproj' - install it with `gem install xcodeproj` or see https://github.com/CocoaPods/Xcodeproj"
    }

}
